version: '3'
services:
    ui:
        build:
            context: ui
        volumes:
           - './ui:/app'
           - '/app/node_modules'
        environment:
           - CHOKIDAR_USEPOLLING=true
        ports:
          - 8080:8080

    api:
        build:
            context: api
        stop_signal: SIGINT
        volumes:
            - "./api:/app"
        ports:
          - 5050:5000

    testdb:
        image: mongo:5.0
        volumes:
            - testdb:/data/db
            # only needed after first time creating volume testdb
            - ./testdb-dump:/testdb-dump
        ports:
            - 27017:27017

    testwebserver:
        image: nginx
        volumes:
            - ./testwebserver/nginx.conf:/etc/nginx/nginx.conf
            - ./testwebserver/testdata:/usr/share/nginx/html
            - ./data/fonts:/usr/share/nginx/html/fonts
        ports:
            - 9000:9000

volumes:
    testdb:
